### ISSUE TITLE
Optimize code 

### ISSUE THREAD

**Issue by gnanesh-16** [gnanesh-16/Automated_gigglethon#2]
1. add Optimized code to work.
2. add Name to Contribution File 
3. **Access** here [gnanesh-16/Automated_gigglethon/blob/main/Contribution.txt](https://github.com/gnanesh-16/Automated_gigglethon/blob/main/Contribution.txt)

**Comment by 2110049135-NITHIN** [comment]
Hey i have added code

**Comment by gnanesh-16** [comment]
> Hey i have added code

That's Awesome kindly do pull Request.
